name: Draft Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    uses: './.github/workflows/build.yml'
  draft:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Create Draft
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="Release v$tag" \
            --draft \
            main.js manifest.json styles.css
